### PR TITLE
[FIX] updates Button small variant padding

### LINKED ISSUE #681: 🐞[Bug] Button small variant incorrect padding
The `small` variant of the button is not applying the correct padding.

Should have `3px 10px` padding, currently has `6px 12px`

### PR DESCRIPTION
**Pull request by alanbsmith**
• resolves issue 

Describe your changes here.

Closes #681 

### Screenshots

Gatsby docs running in Chrome:
Screen Shot 2020-02-03 at 1 09 45 AM

### Merge checklist
- [ ] Added or updated TypeScript definitions (`index.d.ts`) if necessary
- [ ] Added/updated tests
- [ ] Added/updated documentation
- [x ] Tested in Chrome
- [x ] Tested in Firefox
- [x ] Tested in Safari
- [ ] Tested in Edge

Take a look at the [What we look for in reviews](https://github.com/primer/components/blob/master/CONTRIBUTING.md#what-we-look-for-in-reviews) section of the contibuting guidelines for more infomation on how we review PRs.

### CODE REVIEW

File: src/Button.js [hunk 1]
```diff
@@ -9,6 +9,7 @@ import systemPropTypes from '@styled-system/prop-types'
 const variants = variant({
   variants: {
     small: {
+      p: '3px 10px',
```
Comment (alanbsmith) [inline src/Button.js]: I saw other components, like `TextInput` use separate `px` and `py` props, but this directly replaced the `padding` in `buttonStyles`. Happy to update it if you'd like though.
