### PR TITLE
Fix default font weight & size in Heading

### LINKED ISSUE #402: Header h1 font-weight incorrect
Flagged this in https://github.com/primer/design/issues/28

The `h1` in the header of Primer Components has a `font-weight` of `700` and should be set to `600`.

### PR DESCRIPTION
**Pull request by emplums**
Sets the default font weight for the `Heading` component to `600` and moves the default text size into the styled-component declaration

Closes #402 

#### Merge checklist
- [ ] Changed base branch to release branch
- [ ] Tested in Chrome
- [ ] Tested in Firefox
- [ ] Tested in Safari
- [ ] Tested in Edge

### CODE REVIEW

File: src/Heading.js [hunk 1]
```diff
@@ -1,16 +1,17 @@
 import styled from 'styled-components'
 import PropTypes from 'prop-types'
-import {TYPOGRAPHY, COMMON, Base} from './constants'
+import {TYPOGRAPHY, COMMON, Base, get} from './constants'
 import theme from './theme'
 
 const Heading = styled(Base)`
+  font-weight: ${get('fontWeights.bold')};
+  font-size: ${get('fontSizes.5')};
```
Comment (colebemis) [inline src/Heading.js]: Is there a heuristic for deciding whether to set default styles in the `styled` call vs in `defaultProps`?

Comment (emplums) [reply src/Heading.js]: Yeah so, if you set the default in `defaultProps` you can't pull custom theme values from a user provided theme, so ideally default values should always be set in `styled` if you'd like to be able to do that. For the margin value here tbh I should probably move that into `styled` as well

Comment (colebemis) [reply src/Heading.js]: Oh gotcha. That makes sense 👍
