### PR TITLE
SideNav: adding box-shadow under focus pseudo selector (#1219)

### LINKED ISSUE #1219: SideNav's focus state is hard to see
**Describe the bug**

Focus state is hard to see in the `SideNav` component.

**To Reproduce**
1. Go to https://primer.style/components/SideNav
2. Click on the menu to focus
3. Use `tab` key to change focus

**Expected behavior**
It should be easy to see which item has focus. The subtle change in background color might not be enough to draw attention.

**Screenshots**
Screen Shot 2021-05-11 at 18 02 40

**Additional context**
Primer CSS has a proposal to use the `state-focus-shadow` from Primitives to add that blue `box-shadow` instead of the subtle background color. See https://github.com/primer/css/pull/1391.

image

### PR DESCRIPTION
**Pull request by stephenotalora**
Describe your changes here.

Closes #1219 - `SideNav` focus state is hard to see, the purpose of this PR is to bring the component closer to the Primer CSS proposal to use `state-focus-shadow` to add a blue `box-shadow` instead of the subtle background color. For more details on the merged proposal please see primer/css#1391

### Screenshots

Before:

https://user-images.githubusercontent.com/6519974/118313173-424fdb80-b4a7-11eb-800b-3ce4364eec4c.mov

After: 

https://user-images.githubusercontent.com/6519974/118313146-3a903700-b4a7-11eb-970f-a97dcde12752.mov

 

### Merge checklist
- [x] Added/updated tests
- [ ] Added/updated documentation
- [x] Tested in Chrome
- [x] Tested in Firefox - primer component example needs tab index
- [x] Tested in Safari - primer component example needs tab index
- [ ] Tested in Edge

Take a look at the [What we look for in reviews](https://github.com/primer/components/blob/main/contributor-docs/CONTRIBUTING.md#what-we-look-for-in-reviews) section of the contributing guidelines for more information on how we review PRs.

### CODE REVIEW

File: src/SideNav.tsx [hunk 1]
```diff
@@ -97,6 +103,13 @@ const SideNavLink = styled(Link).attrs<StyledSideNavLinkProps>(props => {
 
     &:first-child {
       border-top: 0;
+      border-top-right-radius: ${get('radii.2')};
+      border-top-left-radius: ${get('radii.2')};
```
Comment (stephenotalora) [inline src/SideNav.tsx:107]: I've move this down from  lines 82 - 91 due do to the following:

Screen Shot 2021-05-13 at 8 46 55 PM

for the lightweight version

File: .changeset/dull-radios-shave.md [hunk 2]
```diff
@@ -0,0 +1,5 @@
+---
+'@primer/components': patch
+---
+
+brings `SideNav` closer to the Primer CSS proposal to use state-focus-shadow for the component `SideNavLink` focus state
```
Comment (colebemis) [inline .changeset/dull-radios-shave.md:5]: Change focus state style of `SideNav.Link`

**Review by colebemis — APPROVED** [review]
Thank you, @stephenotalora! ✨ So much better.
